# Generated by Django 5.0.1 on 2024-01-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0003_book_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
